services:
  db:
    image: postgres:17.5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: whalebone
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build:
      context: app
      dockerfile: Dockerfile
    command: flask run --host 0.0.0.0 --port 8000
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/postgres



  proxy:
    build:
      context: proxy
      dockerfile: Dockerfile
    ports:
      - 80:80

volumes:
  db-data:
